-- ============================================================
-- D1 列级迁移脚本
--
-- 此文件由 GitHub Actions workflow 用 `wrangler d1 execute --file` 整体执行。
-- D1 在 --file 模式下遇到错误会中止后续语句，所以这个文件只放
-- "一定成功"的语句（INSERT OR IGNORE / UPDATE）。ALTER TABLE 语句在
-- workflow 中逐条用 --command 执行（每条带 || true 兜底）。
--
-- 新增列时：在 workflow 的 "Run D1 migrations" 步骤追加 ALTER TABLE 语句。
-- 新增 seed 数据时：在下方追加 INSERT OR IGNORE 语句。
-- ============================================================

-- --- domain_providers 种子数据（幂等）---
-- D1 不支持 INSERT ... ON CONFLICT，用 INSERT OR IGNORE 兜底。
-- registration_steps / credential_fields 是 JSON 字符串，单引号转义为 ''。
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('dnshe', 'DNSHE', 'https://api005.dnshe.com/index.php', 'header', 'domains.list,domains.register,domains.delete,domains.renew,dns.list,dns.create,dns.update,dns.delete,quota', 'https://my.dnshe.com/knowledgebase/13/DNSHE%E5%85%8D%E8%B4%B9%E5%9F%9F%E5%90%8DAPI%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3V2.0.html', 'https://my.dnshe.com/register.php', 'https://my.dnshe.com/go.php?code=KRDQzaIlJb', 'GLOBAL', '免费子域名注册平台, 支持 200+ 根域名后缀, 自带 DNS 解析与 Cloudflare 接入', '免费子域名, 默认 1 年有效期, 续期消耗 9.90 信用点', '[{"title":"注册 DNSHE 账号","detail":"访问 my.dnshe.com, 用邮箱注册并完成邮箱验证 (个人/企业均可)"},{"title":"前往「免费域名管理」","detail":"登录客户区 → 左侧导航「免费域名管理」→ 进入域名管理面板"},{"title":"创建 API Key","detail":"在「API 管理」→「创建 API Key」, 填写 Key 名称后保存。⚠️ api_secret 仅显示一次, 请立即复制保存"},{"title":"查看可用根域名","detail":"在域名列表页可看到所有可注册的根域名 (如 dnshe.com, 等), 选一个心仪的根域名"},{"title":"配置到本系统","detail":"将 API Key + API Secret 填入下方表单, 即可在本系统内注册/管理子域名 + 配置 DNS 解析"}]', '[{"key":"api_key","label":"API Key","type":"text","required":true,"placeholder":"cfsd_xxxxxxxxxx","help":"在 DNSHE 客户区「API 管理」页面创建, 以 cfsd_ 开头"},{"key":"api_secret","label":"API Secret","type":"password","required":true,"placeholder":"创建 API Key 时仅显示一次, 请妥善保存","help":"⚠️ 创建时只显示一次, 丢失需重新生成"}]', 1, 1);
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('porkbun', 'Porkbun', 'https://api.porkbun.com/api/json/v3', 'bearer', 'domains.list,dns.list,dns.create,dns.update,dns.delete', 'https://porkbun.com/api/apiDoc', 'https://porkbun.com/account/register', 'https://porkbun.com/', 'GLOBAL', '海外低成本域名注册商, 价格透明无续费涨价, 免费 WHOIS 隐私 + SSL', '按年付费注册, 价格透明 (如 .com $10.48/年, 续费同价)', '[{"title":"注册 Porkbun 账号","detail":"访问 porkbun.com/account/register, 用邮箱注册并验证"},{"title":"添加域名到购物车","detail":"搜索心仪域名, 加入购物车并完成付款 (支持支付宝/PayPal/信用卡)"},{"title":"进入 API Access 页面","detail":"登录后 → Account → API Access → 点击「Create API Key」"},{"title":"保存 API Key + Secret","detail":"系统会同时显示 apikey + secretapi, ⚠️ secretapi 仅显示一次, 请立即复制保存"},{"title":"配置到本系统","detail":"将 apikey + secretapi 填入下方表单, 即可在本系统内管理 Porkbun 域名 + DNS 记录"}]', '[{"key":"api_key","label":"API Key","type":"text","required":true,"placeholder":"pk1_xxxxxxxxxx","help":"在 Porkbun Account → API Access 页面创建, 以 pk1_ 开头"},{"key":"api_secret","label":"Secret API Key","type":"password","required":true,"placeholder":"sk1_xxxxxxxxxx","help":"⚠️ 创建时仅显示一次, 丢失需重新生成"}]', 0, 1);
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('namesilo', 'Namesilo', 'https://www.namesilo.com/api/', 'query', 'domains.list,domains.register,domains.renew,dns.list,dns.create,dns.update,dns.delete', 'https://www.namesilo.com/api-reference', 'https://www.namesilo.com/create-account', 'https://www.namesilo.com/', 'GLOBAL', 'ICANN 认证域名注册商, 免费 WHOIS 隐私保护, 价格含税透明', '按年付费注册, 价格透明 (如 .com $10.95/年)', '[{"title":"注册 Namesilo 账号","detail":"访问 namesilo.com/create-account, 用邮箱注册并验证"},{"title":"充值或绑定支付方式","detail":"在 Account → Billing 添加 PayPal/信用卡, 确保账户有余额或有效支付方式"},{"title":"生成 API Key","detail":"Account → API Manager → 点击「Generate API Key」, 复制生成的 key"},{"title":"IP 白名单 (可选但推荐)","detail":"在 API Manager 页面可设置允许调用 API 的 IP 白名单, 提升安全性"},{"title":"配置到本系统","detail":"将 API Key 填入下方表单 (Namesilo 只需一个 key), 即可在本系统内管理域名 + DNS"}]', '[{"key":"api_key","label":"API Key","type":"password","required":true,"placeholder":"在 API Manager 生成的 key (16 位字符)","help":"只需一个 API Key, 在 Account → API Manager 生成"}]', 0, 1);
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('namecheap', 'Namecheap', 'https://api.namecheap.com/xml.response', 'query', 'domains.list,domains.register,domains.renew,dns.list,dns.create,dns.update,dns.delete', 'https://www.namecheap.com/support/api/methods/', 'https://www.namecheap.com/myaccount/signup/', 'https://www.namecheap.com/', 'GLOBAL', '海外主流域名注册商, 价格亲民, 首年优惠多, 续费略涨', '按年付费, 首年优惠 (如 .com 首年 $7.98, 续费 $10.98)', '[{"title":"注册 Namecheap 账号","detail":"访问 namecheap.com, 用邮箱注册并验证 (需手机号验证)"},{"title":"启用 API 访问","detail":"登录后 → Profile → Tools → API Access → 勾选「Enable API」"},{"title":"配置 IP 白名单","detail":"⚠️ Namecheap 强制要求 IP 白名单, 在 API Access 页面填入本服务器公网 IP"},{"title":"记录 ApiUser + ApiKey","detail":"ApiUser = 登录用户名, ApiKey = 在 API Access 页面生成的密钥, ⚠️ 务必复制保存"},{"title":"配置到本系统","detail":"将 ApiUser + ApiKey 填入下方表单 (两者均必填), 即可在本系统内管理 Namecheap 域名"}]', '[{"key":"api_user","label":"ApiUser","type":"text","required":true,"placeholder":"Namecheap 登录用户名","help":"与登录账号相同的用户名"},{"key":"api_key","label":"API Key","type":"password","required":true,"placeholder":"在 API Access 页面生成的密钥","help":"⚠️ 务必先配置 IP 白名单, 否则 API 调用会返回 105 错误"}]', 0, 1);
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('godaddy', 'GoDaddy', 'https://api.godaddy.com/v1', 'bearer', 'domains.list,domains.renew,dns.list,dns.create,dns.update,dns.delete', 'https://developer.godaddy.com/doc', 'https://sso.godaddy.com/account/create', 'https://www.godaddy.com/', 'GLOBAL', '全球最大 ICANN 认证域名注册商, 品牌知名度高, 首年优惠力度大', '按年付费, 首年大额优惠 (如 .com 首年 $1.99, 续费 $20+)', '[{"title":"注册 GoDaddy 账号","detail":"访问 godaddy.com, 用邮箱注册并完成验证"},{"title":"进入 Developer Portal","detail":"访问 developer.godaddy.com, 登录后 → Keys → 点击「Create New Key」"},{"title":"选择环境 + 创建 Key","detail":"选择 Production 环境 (不是 OTE 测试环境), 填写 Key Name 后生成"},{"title":"保存 Key + Secret","detail":"⚠️ GoDaddy 会同时显示 Key + Secret, Secret 仅显示一次, 请立即复制保存"},{"title":"配置到本系统","detail":"将 Key 填入 API Key, Secret 填入 API Secret (GoDaddy 用 sso-key Key:Secret 格式认证)"}]', '[{"key":"api_key","label":"Key","type":"text","required":true,"placeholder":"Production 环境的 Key","help":"在 developer.godaddy.com → Keys 创建, ⚠️ 选 Production 不是 OTE"},{"key":"api_secret","label":"Secret","type":"password","required":true,"placeholder":"与 Key 配套的 Secret","help":"⚠️ 仅显示一次, 丢失需重新生成 Key"}]', 0, 1);
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('dynadot', 'Dynadot', 'https://api.dynadot.com/api3.json', 'query', 'domains.list,domains.register,domains.renew,dns.list,dns.create,dns.update,dns.delete', 'https://www.dynadot.com/domain/api3-doc.html', 'https://www.dynadot.com/account/create', 'https://www.dynadot.com/', 'GLOBAL', '域名投资者青睐的注册商, 支持批量操作 + 域名交易市场', '按年付费, 价格中等 (如 .com $11.99/年), 转入优惠多', '[{"title":"注册 Dynadot 账号","detail":"访问 dynadot.com/account/create, 用邮箱注册并验证"},{"title":"充值账户余额","detail":"在 Account → Add Funds 添加余额 (支持 PayPal/信用卡/银行转账)"},{"title":"生成 API Key","detail":"Account → API Settings → 点击「Generate API Key」, 复制生成的 key (32 位字符)"},{"title":"查看 API 文档","detail":"访问 dynadot.com/domain/api3-doc.html 了解各 API 命令 (list, register, set_dns 等)"},{"title":"配置到本系统","detail":"将 API Key 填入下方表单 (Dynadot 只需一个 key), 即可在本系统内管理域名 + DNS"}]', '[{"key":"api_key","label":"API Key","type":"password","required":true,"placeholder":"在 API Settings 生成的 key (32 位字符)","help":"只需一个 API Key, 在 Account → API Settings 生成"}]', 0, 1);
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('aliyun', '阿里云', 'https://domain.aliyuncs.com', 'bearer', 'domains.list,domains.register,domains.renew,dns.list,dns.create,dns.update,dns.delete,quota', 'https://help.aliyun.com/document_detail/89847.html', 'https://account.aliyun.com/register/register.htm', 'https://www.aliyun.com/', 'CN', '国内最大域名注册商, 备案便利, 解析稳定, 支持 .cn/.com 等所有主流后缀', '按年付费, 首年优惠 (如 .com 首年 ¥35, 续费 ¥69), 需实名认证', '[{"title":"注册阿里云账号","detail":"访问 aliyun.com, 用手机号注册并完成实名认证 (个人/企业均可)"},{"title":"申请 AccessKey","detail":"登录控制台 → 右上角头像 → AccessKey 管理 → 创建 AccessKey (建议使用子账号 + RAM 权限策略)"},{"title":"保存 AccessKeyId + Secret","detail":"⚠️ AccessKeySecret 仅显示一次, 请立即下载 CSV 或复制保存"},{"title":"配置域名权限","detail":"为该 AccessKey 添加 AliyunDomainFullAccess 系统策略 (或自定义策略仅授权域名相关 API)"},{"title":"配置到本系统","detail":"将 AccessKeyId 填入 API Key, AccessKeySecret 填入 API Secret, 即可在本系统内管理阿里云域名"}]', '[{"key":"api_key","label":"AccessKeyId","type":"text","required":true,"placeholder":"LTAI5tXXXXXXXXXX","help":"在阿里云控制台 AccessKey 管理创建, 建议用子账号"},{"key":"api_secret","label":"AccessKeySecret","type":"password","required":true,"placeholder":"与 AccessKeyId 配套的 Secret","help":"⚠️ 创建时仅显示一次, 务必立即保存"}]', 0, 1);
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('tencent', '腾讯云', 'https://dnspod.tencentcloudapi.com', 'bearer', 'domains.list,domains.register,domains.renew,dns.list,dns.create,dns.update,dns.delete,quota', 'https://cloud.tencent.com/document/product/1427', 'https://cloud.tencent.com/register', 'https://cloud.tencent.com/', 'CN', '国内主流域名注册商, 与 DNSPod 解析深度集成, 支持 .cn/.com 等所有主流后缀', '按年付费, 首年优惠 (如 .com 首年 ¥35, 续费 ¥69), 需实名认证', '[{"title":"注册腾讯云账号","detail":"访问 cloud.tencent.com, 用微信/邮箱注册并完成实名认证 (个人/企业均可)"},{"title":"申请 API 密钥","detail":"登录控制台 → 右上角头像 → 访问管理 → API 密钥管理 → 新建密钥 (建议使用子账号 + CAM 权限)"},{"title":"保存 SecretId + SecretKey","detail":"⚠️ SecretKey 仅显示一次, 请立即复制保存, 否则只能重置"},{"title":"配置域名权限","detail":"为该子账号添加 QcloudDomainPodFullAccess 策略 (或自定义策略仅授权域名相关 API)"},{"title":"配置到本系统","detail":"将 SecretId 填入 API Key, SecretKey 填入 API Secret, 即可在本系统内管理腾讯云域名 + DNSPod 解析"}]', '[{"key":"api_key","label":"SecretId","type":"text","required":true,"placeholder":"AKIDXXXXXXXXXX","help":"在腾讯云访问管理 → API 密钥管理创建, 建议用子账号"},{"key":"api_secret","label":"SecretKey","type":"password","required":true,"placeholder":"与 SecretId 配套的 SecretKey","help":"⚠️ 创建时仅显示一次, 务必立即保存"}]', 0, 1);
INSERT OR IGNORE INTO domain_providers (code, name, api_base_url, auth_type, capabilities, doc_url, register_url, promo_url, regions, description, commission_model, registration_steps, credential_fields, is_default, enabled) VALUES ('cloudflare', 'Cloudflare Registrar', 'https://api.cloudflare.com/client/v4', 'bearer', 'domains.list,domains.register,domains.renew,dns.list,dns.create,dns.update,dns.delete,quota', 'https://developers.cloudflare.com/api/resources/registrar/', 'https://dash.cloudflare.com/?to=/:account/domains', 'https://www.cloudflare.com/products/registrar/', 'GLOBAL', 'Cloudflare 自营域名注册商, 成本价续费 (无加价), 与 CF 生态深度集成', '按年付费, 成本价 (如 .com $10.11/年, 续费同价, 不加价)', '[{"title":"注册 Cloudflare 账号","detail":"访问 dash.cloudflare.com/sign-up, 用邮箱注册 (免费)"},{"title":"添加域名到 Cloudflare","detail":"在 Dashboard → Add a site, 输入域名并完成 NS 切换 (域名需先在其它注册商购买后转入 CF)"},{"title":"创建 API Token","detail":"Profile → API Tokens → Create Token → 选择「Edit zone DNS」模板或自定义"},{"title":"配置 Token 权限","detail":"建议权限: Zone → DNS → Edit + Account → Account Settings → Read (按需添加 Registrar → Edit)"},{"title":"配置到本系统","detail":"将 API Token 填入 API Key (CF 只需 Token, Secret 留空), 即可在本系统内管理 CF 域名 + DNS"}]', '[{"key":"api_key","label":"API Token","type":"password","required":true,"placeholder":"在 Profile → API Tokens 创建的 Token","help":"建议使用细粒度 API Token 而非 Global API Key"}]', 0, 1);

-- 回填已存在行的空字段（COALESCE(NULLIF(...), ?) 只在字段为空时写入，不会覆盖用户编辑）
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://my.dnshe.com/register.php'), description = COALESCE(NULLIF(description, ''), '免费子域名注册平台, 支持 200+ 根域名后缀, 自带 DNS 解析与 Cloudflare 接入'), commission_model = COALESCE(NULLIF(commission_model, ''), '免费子域名, 默认 1 年有效期, 续期消耗 9.90 信用点') WHERE code = 'dnshe';
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://porkbun.com/account/register'), description = COALESCE(NULLIF(description, ''), '海外低成本域名注册商, 价格透明无续费涨价, 免费 WHOIS 隐私 + SSL'), commission_model = COALESCE(NULLIF(commission_model, ''), '按年付费注册, 价格透明 (如 .com $10.48/年, 续费同价)') WHERE code = 'porkbun';
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://www.namesilo.com/create-account'), description = COALESCE(NULLIF(description, ''), 'ICANN 认证域名注册商, 免费 WHOIS 隐私保护, 价格含税透明'), commission_model = COALESCE(NULLIF(commission_model, ''), '按年付费注册, 价格透明 (如 .com $10.95/年)') WHERE code = 'namesilo';
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://www.namecheap.com/myaccount/signup/'), description = COALESCE(NULLIF(description, ''), '海外主流域名注册商, 价格亲民, 首年优惠多, 续费略涨'), commission_model = COALESCE(NULLIF(commission_model, ''), '按年付费, 首年优惠 (如 .com 首年 $7.98, 续费 $10.98)') WHERE code = 'namecheap';
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://sso.godaddy.com/account/create'), description = COALESCE(NULLIF(description, ''), '全球最大 ICANN 认证域名注册商, 品牌知名度高, 首年优惠力度大'), commission_model = COALESCE(NULLIF(commission_model, ''), '按年付费, 首年大额优惠 (如 .com 首年 $1.99, 续费 $20+)') WHERE code = 'godaddy';
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://www.dynadot.com/account/create'), description = COALESCE(NULLIF(description, ''), '域名投资者青睐的注册商, 支持批量操作 + 域名交易市场'), commission_model = COALESCE(NULLIF(commission_model, ''), '按年付费, 价格中等 (如 .com $11.99/年), 转入优惠多') WHERE code = 'dynadot';
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://account.aliyun.com/register/register.htm'), description = COALESCE(NULLIF(description, ''), '国内最大域名注册商, 备案便利, 解析稳定, 支持 .cn/.com 等所有主流后缀'), commission_model = COALESCE(NULLIF(commission_model, ''), '按年付费, 首年优惠 (如 .com 首年 ¥35, 续费 ¥69), 需实名认证') WHERE code = 'aliyun';
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://cloud.tencent.com/register'), description = COALESCE(NULLIF(description, ''), '国内主流域名注册商, 与 DNSPod 解析深度集成, 支持 .cn/.com 等所有主流后缀'), commission_model = COALESCE(NULLIF(commission_model, ''), '按年付费, 首年优惠 (如 .com 首年 ¥35, 续费 ¥69), 需实名认证') WHERE code = 'tencent';
UPDATE domain_providers SET register_url = COALESCE(NULLIF(register_url, ''), 'https://dash.cloudflare.com/?to=/:account/domains'), description = COALESCE(NULLIF(description, ''), 'Cloudflare 自营域名注册商, 成本价续费 (无加价), 与 CF 生态深度集成'), commission_model = COALESCE(NULLIF(commission_model, ''), '按年付费, 成本价 (如 .com $10.11/年, 续费同价, 不加价)') WHERE code = 'cloudflare';
